export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const LOGOUT = 'LOGOUT';

export const CENTRAL_REQUEST = 'CENTRAL_REQUEST';
export const CENTRAL_SUCCESS = 'CENTRAL_SUCCESS';
export const CENTRAL_FAILURE = 'CENTRAL_FAILURE';

export const ADD_CENTRAL_USER_REQUEST = 'ADD_CENTRAL_USER_REQUEST';
export const ADD_CENTRAL_USER_SUCCESS = 'ADD_CENTRAL_USER_SUCCESS';
export const ADD_CENTRAL_USER_FAILURE = 'ADD_CENTRAL_USER_FAILURE';

export const ADD_STORE_REQUEST = 'ADD_STORE_REQUEST';
export const ADD_STORE_SUCCESS = 'ADD_STORE_SUCCESS';
export const ADD_STORE_FAILURE = 'ADD_STORE_FAILURE';

export const MENU_REQUEST = 'MENU_REQUEST';
export const MENU_SUCCESS = 'MENU_SUCCESS';
export const MENU_FAILURE = 'MENU_FAILURE';

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const COMPONENT_REQUEST = 'COMPONENT_REQUEST';
export const COMPONENT_SUCCESS = 'COMPONENT_SUCCESS';
export const COMPONENT_FAILURE = 'COMPONENT_FAILURE';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

export const ADD_COMPONENT_REQUEST = 'ADD_COMPONENT_REQUEST';
export const ADD_COMPONENT_SUCCESS = 'ADD_COMPONENT_SUCCESS';
export const ADD_COMPONENT_FAILURE = 'ADD_COMPONENT_FAILURE';

export const DELETE_OBJECT_REQUEST = 'DELETE_OBJECT_REQUEST';
export const DELETE_OBJECT_SUCCESS = 'DELETE_OBJECT_SUCCESS';
export const DELETE_OBJECT_FAILURE = 'DELETE_OBJECT_FAILURE';
