export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const CENTRAL_REQUEST = 'CENTRAL_REQUEST';
export const CENTRAL_SUCCESS = 'CENTRAL_SUCCESS';
export const CENTRAL_FAILURE = 'CENTRAL_FAILURE';
