export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const LOGOUT = 'LOGOUT';

export const CENTRAL_REQUEST = 'CENTRAL_REQUEST';
export const CENTRAL_SUCCESS = 'CENTRAL_SUCCESS';
export const CENTRAL_FAILURE = 'CENTRAL_FAILURE';

export const ADD_CENTRAL_USER_REQUEST = 'ADD_CENTRAL_USER_REQUEST';
export const ADD_CENTRAL_USER_SUCCESS = 'ADD_CENTRAL_USER_SUCCESS';
export const ADD_CENTRAL_USER_FAILURE = 'ADD_CENTRAL_USER_FAILURE';

export const ADD_STORE_REQUEST = 'ADD_STORE_REQUEST';
export const ADD_STORE_SUCCESS = 'ADD_STORE_SUCCESS';
export const ADD_STORE_FAILURE = 'ADD_STORE_FAILURE';
